---
# tasks file for backend

- name: Install necessary dependencies to provision backend servers
  import_tasks: install_dependencies.yml

- name: Perform steps necessary to install docker
  import_tasks: install_docker.yml

- name: Run backend docker image
  import_tasks: docker_run.yml