# -*- mode: ruby -*-
# vi: set ft=ruby :

# IP for the VM where the Backend is going to be executed
BackendIP = "10.0.0.8"
# IP for the VM where the Frontend is going to be executed
FrontendIP = "10.0.0.10"
# IP for the VM where the Database is going to be executed
DatabaseIP = "10.0.0.12"

Vagrant.configure("2") do |config|

  config.vm.synced_folder "../shared", "/home/vagrant/shared"

  # Define database
  config.vm.define "database" do |database|
    database.vm.box = "ubuntu/trusty64"
    database.vm.network "forwarded_port", guest: 3306, host: 3306

    # This gives the backend instance a static IP, to ease network communication
    database.vm.network :private_network, ip: DatabaseIP

    database.vm.provision :shell, path: "Provision-database.sh"

  end

  # Define backend
  config.vm.define "backend" do |backend|
    backend.vm.box = "ubuntu/trusty64"
    backend.vm.network "forwarded_port", guest: 3000, host: 3000

    # This gives the backend instance a static IP, to ease network communication
    backend.vm.network :private_network, ip: BackendIP

    backend.vm.provision :shell, path: "Provision-backend.sh", env: {"DB_HOST" => DatabaseIP, "DB_USER" => 'root', "DB_PASS" => 'ubuntu'}

  end

  # Define frontend
  config.vm.define "frontend" do |frontend|
    frontend.vm.box = "ubuntu/trusty64"
    frontend.vm.network "forwarded_port", guest: 3030, host: 3030

    # This gives the backend instance a static IP, to ease network communication
    frontend.vm.network :private_network, ip: FrontendIP

    frontend.vm.provision :shell, path: "Provision-frontend.sh", env: {"BACK_HOST" => BackendIP}

  end

end
