- name: Restore database
  mysql_db:
    login_host: "{{db_host}}"
    login_user: "{{db_user}}"
    login_password: "{{db_pass}}"
    name: movie_db
    state: import
    target: /home/ubuntu/ansible/table_creation_and_inserts.sql
