---

- name: Run docker front container
  become: yes
  community.docker.docker_container:
    name: frontend
    image: "{{docker_image}}"
    ports:
      - "3030:3030"
    detach: yes
    pull: true