---

- name: Run docker front container
  become: yes
  community.docker.docker_container:
    name: frontend
    image: "{{docker_image}}:latest"
    ports:
      - "3030:3030"
    env:
      BACK_HOST: "{{back_host}}"
    detach: yes
    pull: true