pipeline { 
    agent { docker { image 'node:current-alpine' } }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Test'){
            steps {
                sh 'npm install'
                sh 'npm test'
            }
        }
        stage('Build') {
            steps {
                sh 'docker build'
            }
        }
        stage('Push') {
            steps {
                sh 'docker push' //credentials
            }
        }
        stage('Clean') {
            steps {
                // remove previous image of docker local
            }
        }
        stage('Pull') {
            steps {
                sh 'docker pull'
            }
        }
        stage('Deploy') {
            steps {
                // call to ansible
            }
        }
    }
}